# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature', models.CharField(blank=True, default=0, max_length=5, null=True)),
                ('weather', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
